<!-- Criado por Djonathan Quadras -->

# Questão 3 {-}

Escolher duas questões do GRUPO I e duas questões do GRUPO II, de temas diferentes. Justificar todas as respostas. O professor não “lerá” o subentendido. Expliquem como se estivessem explanando para um colega que não foi às aulas e não está sabendo o assunto. 


## Questões Grupo 1 {-}

(4) Em relação aos ensaios de curto-circuito (CC) e de circuito aberto (CA) em transformadores é correto afirmar (Falso ou
Verdadeiro):

a. ( ) O ensaio de curto-circuito é necessário para se obter o rendimento do transformador no caso de se trabalhar com o modelo impedância série do transformador de potência, pois, fornece o valor das perdas no núcleo, necessário para o cálculo do rendimento do dispositivo.
b. ( ) Vários ensaios são necessários para se obter as características de funcionamento e os parâmetros de um transformador de potência, como os ensaios de curto-circuito e de circuito aberto. Se o transformador for usado em corrente contínua como, por exemplo, promovendo o isolamento para corrente contínua entre circuitos, mas, se mantendo a continuidade para corrente alternada, o ensaio de polaridade também passa a ser importante. 
c. ( ) O que se espera no ensaio de circuito aberto é uma alta impedância do transformador. Ao contrário, no ensaio de curtocircuito, uma baixa impedância é procurada, sendo que “alta” e “baixa” são consideradas em relação ao valor da impedância da carga. 
d. ( ) As normas recomendam que o ensaio de CC seja realizado pelo lado de alta tensão e o de CA pelo lado de baixa tensão.
e. ( ) Se os dois ensaios forem feitos, respectivamente, com corrente nominal e com tensão nominal, as perdas serão obtidas estarão com valores muito próximos aos seus valores reais em operação normal do equipamento, de forma que, no cálculo do rendimento, podem ser utilizadas diretamente, dispensando a obtenção individual de cada perda.

(5) Em relação a transformador, de um modo geral, verificar se são verdadeiras (V) ou falsas (F) as seguintes afirmações:
a. ( ) As harmônicas de corrente surgem da deformação de sua corrente de excitação, devido ao laço de histerese e à saturação do núcleo, possuindo frequências múltiplas da fundamental, com destaque para a terceira harmônica.
b. ( ) A corrente de excitação produz, além do fluxo magnético no núcleo, perdas Joule nesse mesmo núcleo, provocando seu aquecimento.
c. ( ) A corrente de excitação, ou de magnetização, é a responsável pela magnetização do núcleo do transformador e pelas perdas histeréticas e por correntes de Foucault.
d. ( ) Os valores de base de linha e de fase em um sistema trifásico devem manter entre si a mesma relação que as grandezas respectivas em seus valores reais. Após se transformar o sistema trifásico equilibrado em por unidade, obtém-se um sistema monofásico em por unidade, que pode ser resolvido pelas técnicas usuais de circuitos elétricos.
e. ( ) O sistema por unidade (pu) apresenta uma série de vantagens como, por exemplo, deixar os valores da corrente de excitação e da resistência e da reatância de excitação, respectivamente, dentro de faixas relativamente estreitas de valores, independentemente dos valores tomados como base. Outra vantagem é que, apesar de mudar os módulos ou valores eficazes das grandezas, inclusive potências, não altera os ângulos envolvidos entre as grandezas, o que permite a aplicação direta das técnicas de circuitos elétricos para a resolução dos problemas. 


## Respostas - Questões Grupo 1 {-}

(4) Em relação aos ensaios de curto-circuito (CC) e de circuito aberto (CA) em transformadores é correto afirmar (Falso ou
Verdadeiro):

a. (\textcolor{red}{F}) Como as resistências características de $g_m$ e $b_m$ são baixos para o ensiao de curto-circuito, a tensão sobre essas resistências também será muito baixa, tornando o valor de perdas no núcleo (para o ensaio de curto-circuito) praticamente desprezível.
b. (\textcolor{red}{F} ) Não é possível realizar os testes aplicando uma corrente contínua. Um indutor (componente chave para um transformador) se comporta como um circuito aberto diante de uma corrente contínua. Dessa forma, se for aplicada uma cc, os ensaios não irão retornar valores úteis.
c. (\textcolor{green}{V}) de fato, o que se espera no ensaio de circuito aberto é uma alta impedância do transformador, ao contrário do ensaio de curto-circuito. 
d. (\textcolor{green}{V}) De fato, para que haja maior segurança nas medições, as normas recomendam que o ensaio de CC seja realizado pelo lado de alta tensão e o de CA pelo lado de baixa tensão.
e. (\textcolor{red}{F}) As perdas encontradas são as perdas no ferro. Entretanto, não é dispensável a obtenção individual de cada perda.

(5) Em relação a transformador, de um modo geral, verificar se são verdadeiras (V) ou falsas (F) as seguintes afirmações:
a. (\textcolor{green}{V}) De fato, as harmônicas de corrente surgem da deformação de sua corrente de excitação, em deccorência do laço de histerese e à saturação do núcleo. Também é notório que a terceira harmônica aparece com destaque neste cenário.
b. (\textcolor{red}{F}) A corrente de excitação, além do fluxo magnético no núcleo, gera perdas Ôhmicas.
c. (\textcolor{red}{F}) A corrente de excitação não é responsável pelas perdas por histerese e corrente de Foucault. Essas perdas são referentes ao núcleo que possui baixa resistividade elétrica.
d. (\textcolor{green}{V}) De fato, os valores de base de linha e de fase em um sistema trifásico devem manter entre si a mesma relação que as grandezas respectivas em seus valores reais. Dessa forma, é possível se obter um sistema monofásico em por pu após se transformar o sistema trifásico equilibrado em pu.
e. (\textcolor{red}{F}) A representação de um sistema trifásico em p.u. altera sim os ângulos, poir sé feito para uma única fase do sistema em $Y$ ou $Y_{equivalente}$ 

## Questões Grupo 2 {-}

(11) Em relação a um transformador de potência é correto afirmar (Falso ou Verdadeiro):
a. ( ) Para melhorar o seu rendimento, deve ser projetado para que haja uma compatibilidade entre densidade de corrente e a indução no ferro e o custo do equipamento. No caso do ferro, usar ligas ferromagnéticas de alta resistividade e com laço de histerese bastante estreito.
b. ( ) A frase “Para cada 1 MVA de potência gerada por uma usina, são necessários de 6 a 10 MVA de potência em transformadores para que esta energia chegue ao consumidor final” mostra uma interessante constatação prática.
c. ( ) Deseja-se que possuam custo aceitável, com boa regulação de tensão, alto rendimento, baixa corrente de excitação e baixas perdas quando operando em vazio. Baixas correntes em vazio são obtidas com altas indutâncias (reatâncias) de magnetização, característica de núcleos altamente permeáveis. Menores perdas em vazio significam, principalmente, menores perdas no ferro.
d. ( ) Para que se obtenha uma regulação de tensão adequada, deve-se reduzir a queda de tensão no equipamento. Assim, no projeto do transformador, deve-se intensificar o acoplamento magnético entre os enrolamentos, visando-se a redução dos fluxos dispersos, com aproximação entre as bobinas e uso de núcleos ferromagnéticos altamente permeáveis.
e. ( ) O transformador pode ser considerado um grande impulsionador da transmissão econômica de energia elétrica a grandes distâncias, já que propiciou a transmissão em altas tensões, com menores correntes (menores perdas e economia nos condutores).

(19) São falsas ou verdadeiras as proposições a seguir, a respeito da técnica por unidade (pu)?
a. ( ) Se, por exemplo, a queda de tensão na resistência no enrolamento de baixa tensão de um transformador for 0,01pu (por unidade), isso significa que essa queda é 1% da tensão tomada como base para esse circuito. Se essa resistência for transferida para o enrolamento de alta, o valor da queda de tensão continuará sendo 0,01pu, mas, agora, em relação à tensão tomada como base para o enrolamento de alta.
b. ( ) Uma das vantagens do sistema pu (por unidade) é que os parâmetros elétricos de um dado transformador têm valores típicos, não apresentando, portanto, variações significativas em relação a outros transformadores, ainda que as potências nominais dos transformadores comparados variem, desde que os valores de base de cada equipamento sejam os seus valores nominais.
c. ( ) Para o cálculo do rendimento sempre podem ser utilizadas diretamente as grandezas em pu. Embora os valores das potências em pu não sejam os verdadeiros (aqueles em W), os valores do numerador e do denominador da expressão usada para o cálculo do rendimento são proporcionais entre si, de modo que o valor do quociente não se altera.
d. ( ) Dependendo da base escolhida, os valores (numéricos) em pu para o mesmo circuito elétrico serão diferentes entre si, podendo ser maiores ou menores que os valores reais das grandezas envolvidas.
e. ( ) Os valores em pu (por unidade) em um ponto do circuito (lado do transformador) têm os mesmos valores quando transferidos para o outro lado. Isso ocorre porque tanto os valores reais das grandezas, bem como, os valores de base estão relacionados pela mesma relação de transformação.


## Respostas - Questões Grupo 2 {-}

(11) Em relação a um transformador de potência é correto afirmar (Falso ou Verdadeiro):
a. (\textcolor{green}{V}) De fato, para melhorar o seu rendimento, deve ser projetado para que haja uma compatibilidade entre densidade de corrente e a indução no ferro e o custo do equipamento. Usar ligas ferromagnéticas de alta resistividade e com laço de histerese bastante estreito reduz as perdas por histerese e correntes de faucault referentes ao núcleo.
b. (\textcolor{green}{V}) De fato é uma interessante constatação prática, uma vez que apresenta uma margem de 4MVA de potência para atingir o objetivo.
c. (\textcolor{green}{V}) De fato, todas as características apresentadas são relacionadas a um bom transformador. Também é fato que menores perdas em vazio são características de um núcleo de ferro com alta indutância, o que minimiza as perdas por histerese.
d. (\textcolor{green}{V}) De fato, para que haja uma boa regulação é necessário minimizar as perdas magnéticas. Isso é possível aproximando as bobinas e aplicando-as em um núcleo permeável (como citado, um núcleo ferromagnético).
e. (\textcolor{green}{V}) As transmissões de energia elétrica apresentaram um ganho considerável com a aplicação de transformadores, uma vez que se bem dimencionados e utilizando bons componentes, eles minizam as perdas de distribuição.

(19) São falsas ou verdadeiras as proposições a seguir, a respeito da técnica por unidade (pu)?
a. (\textcolor{green}{V}) De fato, considerando a tensão tomada como base igual a 1, uma queda de 0.01pu apresenta uma queda de 1%. E também é fato que as proporções são as mesmas para ambos os lados do circuito.
b. (\textcolor{green}{V}) De fato, a principal vantagem da utilização da técnica pu é a sua proporcionalidade. Dessa forma, contanto que as proporcionalidades se mantenham as mesmas, as potências nominais dos transformadores podem variar.
c. (\textcolor{green}{V}) Novamente, a principal vantagem da técnica pu é a proporcionalidade. Dessa forma, mesmo que os valores aplicados não sejam "reais", a proporcionalidade garante que o rendimento gerará o mesmo valor para ambas as situações.
d. (\textcolor{green}{V}) De fato, os valores numéricos serão alterados de acordo com a base escolhida. Entretanto, não será alterada a proporcionalidade entre eles.
e. (\textcolor{green}{V}) De fato, a proporcionalidade gerada pela técnica pu garante que de ambos os lados do transformador os valores serão iguais.